### ISSUE TITLE
v1.7.0 regression: partial match doesn't seem to work anymore

### ISSUE THREAD

**Issue by volans-** [jamielennox/requests-mock#109] opened 2019-09-24 09:12 UTC
Hi, with the recent release of v1.7.0 I've noticed a regression in my project with partial matching that was working fine with v1.6.0.

Here an example snippet to repro it.

## v1.6.0
```
>>> import requests
>>> import requests_mock
>>> with requests_mock.Mocker() as mocker:
...     mocker.register_uri('GET', 'https://localhost:443/endpoint?query=')
...     requests.get('https://localhost:443/endpoint?query=foo')
...
<requests_mock.adapter._Matcher object at 0x107064a90>
<Response [200]>
```

## v1.7.0
```
>>> import requests
>>> import requests_mock
>>> with requests_mock.Mocker() as mocker:
...     mocker.register_uri('GET', 'https://localhost:443/endpoint?query=')
...     requests.get('https://localhost:443/endpoint?query=foo')
...
<requests_mock.adapter._Matcher object at 0x109d31128>
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File ".venv/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ".venv/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File ".venv/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File ".venv/lib/python3.6/site-packages/requests_mock/mocker.py", line 111, in _fake_send
    return _original_send(session, request, **kwargs)
  File ".venv/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File ".venv/lib/python3.6/site-packages/requests_mock/adapter.py", line 255, in send
    raise exceptions.NoMockAddress(request)
requests_mock.exceptions.NoMockAddress: No mock address: GET https://localhost:443/endpoint?query=foo
```

I've also tried to set `complete_qs=False` to force it without success, although I didn't see any change related to it between the two versions so I guess is not related to that.

**Comment by jamielennox** [comment] 2019-09-25 11:43
Hey - Thanks for the report. Yea, I can say that the reversion is definitely a result of #101 and the complete_qs won't fix it. 

So it's somewhat a regression, but I think it's also fixing a mistaken behaviour so I will need to think about whether we revert this. 

Basically in the old 1.6 code if the query string didn't have a value it was ignored, so register_uri with `?query=` was no different to `?abc=` or anything else. If you were to put `?query=value` then you wouldn't match. 

I'm inclined to say that the new behaviour is the correct one. How much of a problem does this cause for you?

**Comment by volans-** [comment] 2019-09-25 17:58
@jamielennox thanks for the quick reply. My use case is that I want to test some endpoint that supports `?query=foo` and I'd like to register an URI to return the same content for any query, but I'd like to register a different URI for a different keyword, let's say `?name=`.
In this scenario it was very helpful to be able to have partial matching instead of having to register all the possible cases with all the values.

Is there any way to support this use case with the current code?

**Comment by ilcardella** [comment] 2019-09-28 11:51
I had the very same issue and I could not understand why until I checked the Adapter source code.
My current workaround for this problem is passing a regex rather than the URL.

As an example
```
requests_mock.get(re.compile("https://my-url.com/foo?bar="))
```

I would suggest to update the documentation, as at the moment it does not align with the code behaviour.

**Comment by volans-** [comment] 2019-09-29 08:38
I can confirm indeed that using a regex, optionally with `re.escape` if needed, works fine with both previous and current versions of requests_mock.
Feel free to resolve this bug but I suggest too to update the documentation to reflect current behaviour.

**Comment by jamielennox** [comment] 2019-10-07 10:40
So I'd like someone to check for me, but I don't think that partial match works like you think it does and you're hitting a fallback. The short version of the change was setting `keep_blank_values=True`.

Before that the logic was like: 
```python
>>> import urllib.parse
>>> u = urllib.parse.urlparse('https://test.com/path?qs=')
>>> r = urllib.parse.parse_qs(u.query, keep_blank_values=False). # False is default
>>> print(r)
{}
```
vs
```python
>>> import urllib.parse
>>> u = urllib.parse.urlparse('https://test.com/path?qs=')
>>> r = urllib.parse.parse_qs(u.query, keep_blank_values=True)
>>> print(r)
{'qs': ['']}
```
Under 1.6.0 I don't think you're seeing a "partial" match. I think you're seeing that the qs you're trying to match is getting ignored and it happens to fall back to the response you expect.

So i'm thinking the next question is should we add a query string partial matcher and what would that look like?

**Comment by jamielennox** [comment] 2019-10-07 11:05
Oh also - the easiest way to do something custom like this is to set an `additional_matcher` that lets you programatically check whatever you like: https://requests-mock.readthedocs.io/en/latest/matching.html#additional-matchers 

Ironically though, because of the above reasons, this example will work in 1.7.0 but not in 1.6.0: 
```
with requests_mock.Mocker() as mocker:
    mocker.get('https://example.com/endpoint',
               additional_matcher=lambda req: 'abc' in req.qs)
    print(requests.get('https://example.com/endpoint?abc'))
```
`qs` is a dictionary so `in` will just check for the key and be a true partial match.

**Closed** 2020-03-31 14:03 UTC
